name: PreRelease

on:
  push:
    branches:
      - ci-pre

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate CHANGELOG
        id: changelog
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: update CHANGELOG for release ${{ github.ref_name }}'
          file_pattern: CHANGELOG.md

  create_prerelease:
    needs: [generate_changelog]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: beta-${{ github.ref_name }}
          release_name: Beta Release ${{ github.ref_name }}
          body: |
            ## Changes
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: true
  upload:
    needs:
      - create_prerelease
    uses: ./.github/workflows/common-tasks.yml

  publish-python:
#    if: "startsWith(github.ref, 'refs/tags/')"
    uses: ./.github/workflows/python-sdk.yml
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#      - name: build python
#        uses: ./.github/workflows/python-sdk.yml
#      - uses: actions/download-artifact@v3
#        with:
#          name: wheels
#      - name: Publish to PyPI
#        uses: PyO3/maturin-action@v1
#        env:
#          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
#        with:
#          command: upload
#          args: --non-interactive --skip-existing *